name: Hello CI

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo 'Pipeline works!'

  say-goodbye:
    needs: say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Print goodbye
        run: echo 'The first job finished successfully!'
