name: Automated Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11'] # This loops the job twice!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }} # Injects the version dynamically
          
      - name: Install dependencies
        run: pip install -r phase-2/requirements.txt
        
      - name: Lint with Flake8
        run: flake8 . --max-line-length=100
        
      - name: Run Pytest
        run: pytest phase-2/test_calculator.py -v

  build-and-push:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: phase-1/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculator:latest